-- Phase 3 TASK-3.8 接口日志表质量巡检配置、结果与问题明细

CREATE TABLE IF NOT EXISTS argus_interface_log_table_config (
    id                         BIGINT          PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    monitor_config_id          BIGINT          NOT NULL COMMENT '应用监控配置ID',
    project_mapping_id         BIGINT          NOT NULL COMMENT '应用映射ID',
    datasource_id              BIGINT          NOT NULL COMMENT '数据源ID',
    app_name                   VARCHAR(100)    DEFAULT NULL COMMENT '应用名称',
    environment                VARCHAR(50)     NOT NULL DEFAULT 'PROD' COMMENT '环境',
    config_name                VARCHAR(200)    DEFAULT NULL COMMENT '配置名称',
    table_name                 VARCHAR(200)    NOT NULL COMMENT '日志表名',
    primary_key_column         VARCHAR(100)    NOT NULL COMMENT '主键字段',
    interface_code_column      VARCHAR(100)    NOT NULL COMMENT '接口编码字段',
    request_time_column        VARCHAR(100)    NOT NULL COMMENT '请求时间字段',
    response_time_column       VARCHAR(100)    NOT NULL COMMENT '响应时间字段',
    response_body_column       VARCHAR(100)    NOT NULL COMMENT '响应体字段',
    status_code_column         VARCHAR(100)    DEFAULT NULL COMMENT '状态码字段',
    request_id_column          VARCHAR(100)    DEFAULT NULL COMMENT '请求ID字段',
    trace_id_column            VARCHAR(100)    DEFAULT NULL COMMENT 'traceId字段',
    scan_mode                  VARCHAR(30)     NOT NULL DEFAULT 'ID_INCREMENT' COMMENT '扫描模式',
    last_scan_value            VARCHAR(200)    DEFAULT NULL COMMENT '最近扫描位点',
    quality_rules              JSON            DEFAULT NULL COMMENT '质量规则',
    alert_rules                JSON            DEFAULT NULL COMMENT '告警规则',
    enabled                    TINYINT(1)      NOT NULL DEFAULT 1 COMMENT '是否启用',
    create_by                  VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by                  VARCHAR(64)     DEFAULT NULL COMMENT '修改人',
    update_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    UNIQUE KEY uk_datasource_table (datasource_id, table_name),
    INDEX idx_monitor_config (monitor_config_id),
    INDEX idx_project_mapping (project_mapping_id),
    INDEX idx_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='接口日志表质量巡检配置表';

CREATE TABLE IF NOT EXISTS argus_log_quality_check_result (
    id                         BIGINT          PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    log_table_config_id        BIGINT          NOT NULL COMMENT '日志表配置ID',
    monitor_config_id          BIGINT          NOT NULL COMMENT '应用监控配置ID',
    datasource_id              BIGINT          DEFAULT NULL COMMENT '数据源ID',
    app_name                   VARCHAR(100)    DEFAULT NULL COMMENT '应用名称',
    environment                VARCHAR(50)     NOT NULL DEFAULT 'PROD' COMMENT '环境',
    table_name                 VARCHAR(200)    NOT NULL COMMENT '日志表名',
    check_window_start         DATETIME        DEFAULT NULL COMMENT '巡检窗口开始',
    check_window_end           DATETIME        DEFAULT NULL COMMENT '巡检窗口结束',
    total_count                BIGINT          NOT NULL DEFAULT 0 COMMENT '巡检记录数',
    issue_count                BIGINT          NOT NULL DEFAULT 0 COMMENT '问题数',
    quality_score              INT             DEFAULT NULL COMMENT '质量评分',
    quality_level              VARCHAR(2)      DEFAULT NULL COMMENT '质量等级',
    completeness_score         INT             DEFAULT NULL COMMENT '完整性得分',
    timeliness_score           INT             DEFAULT NULL COMMENT '及时性得分',
    uniqueness_score           INT             DEFAULT NULL COMMENT '唯一性得分',
    validity_score             INT             DEFAULT NULL COMMENT '合法性得分',
    consistency_score          INT             DEFAULT NULL COMMENT '一致性得分',
    growth_risk_score          INT             DEFAULT NULL COMMENT '增长风险得分',
    status                     VARCHAR(30)     NOT NULL DEFAULT 'DONE' COMMENT '状态',
    error_message              VARCHAR(1000)   DEFAULT NULL COMMENT '失败原因',
    create_by                  VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by                  VARCHAR(64)     DEFAULT NULL COMMENT '修改人',
    update_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX idx_config_time (log_table_config_id, create_time),
    INDEX idx_app_table (app_name, environment, table_name),
    INDEX idx_level (quality_level, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='日志质量巡检结果表';

CREATE TABLE IF NOT EXISTS argus_log_quality_issue (
    id                         BIGINT          PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    check_result_id            BIGINT          NOT NULL COMMENT '巡检结果ID',
    log_table_config_id        BIGINT          NOT NULL COMMENT '日志表配置ID',
    app_name                   VARCHAR(100)    DEFAULT NULL COMMENT '应用名称',
    environment                VARCHAR(50)     NOT NULL DEFAULT 'PROD' COMMENT '环境',
    table_name                 VARCHAR(200)    NOT NULL COMMENT '日志表名',
    interface_code             VARCHAR(200)    DEFAULT NULL COMMENT '接口编码',
    issue_type                 VARCHAR(50)     NOT NULL COMMENT '问题类型',
    severity                   VARCHAR(10)     NOT NULL COMMENT '严重等级',
    issue_count                BIGINT          NOT NULL DEFAULT 0 COMMENT '问题数量',
    sample_record_id           VARCHAR(200)    DEFAULT NULL COMMENT '样本记录ID',
    sample_payload             JSON            DEFAULT NULL COMMENT '样本摘要',
    description                TEXT            DEFAULT NULL COMMENT '问题描述',
    suggestion                 TEXT            DEFAULT NULL COMMENT '修复建议',
    status                     VARCHAR(30)     NOT NULL DEFAULT 'NEW' COMMENT '状态',
    occurred_at                DATETIME        NOT NULL COMMENT '发生时间',
    create_by                  VARCHAR(64)     DEFAULT NULL COMMENT '创建人',
    create_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by                  VARCHAR(64)     DEFAULT NULL COMMENT '修改人',
    update_time                DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    INDEX idx_result (check_result_id),
    INDEX idx_config_type (log_table_config_id, issue_type),
    INDEX idx_app_time (app_name, environment, occurred_at),
    INDEX idx_status (status, severity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='日志质量问题明细表';
